
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 05 23:04:42 CEST 2004
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 5;
  public static final int TESIS = 4;
  public static final int PORT = 15;
  public static final int XOR = 18;
  public static final int CENT = 37;
  public static final int PUNTOCOMA = 6;
  public static final int OUT = 31;
  public static final int NOT = 21;
  public static final int IS = 12;
  public static final int AND = 16;
  public static final int NAND = 19;
  public static final int NOR = 20;
  public static final int LETRA = 35;
  public static final int IN = 30;
  public static final int OR = 17;
  public static final int BEGIN = 13;
  public static final int SUBRAYA = 8;
  public static final int ASOP = 2;
  public static final int OF = 33;
  public static final int ARCHICT = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int DIGITO = 36;
  public static final int COMA = 7;
  public static final int IDENT = 38;
  public static final int BIT = 26;
  public static final int ARCHITECTURE = 32;
  public static final int AFTER = 25;
  public static final int END = 14;
  public static final int UNO = 23;
  public static final int SIGNA = 29;
  public static final int ENTITY = 10;
  public static final int CERO = 24;
  public static final int STRUCT = 27;
  public static final int APOST = 9;
  public static final int TRANSPORT = 28;
  public static final int NANOSEG = 22;
  public static final int PAREN = 3;
  public static final int SIGNAL = 34;
}

